services:
  pg:
    image: postgres:15.6
    restart: always
    container_name: pg
    volumes:
      - pd-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mrp_db
      POSTGRES_USER: mrp
      POSTGRES_PASSWORD: mrp
    ports:
      - '5432:5432'
    expose:
      - 5432
    healthcheck:
      test: ['CMD', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pd-db-data: