name: uHub
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Env
        run: |
          ssh-keygen -t rsa -b 4096 -m PEM -f keys/jwt.key -N ""
          touch .env
          echo NODE_ENV=development >> .env
          echo COOKIENAME=ERPCOOKIE >> .env
          echo COOKIE_SAMESITE=lax >> .env
          echo FRONTEND_URL="*" >> .env
          echo PORT=4000 >> .env
          echo DB_HOST=localhost >> .env
          echo DB_USERNAME=mrp >> .env
          echo DB_PASSWORD=mrp >> .env
          echo DB_DATABASE=mrp_db >> .env
          echo DB_PORT=5432 >> .env
          echo "PUB_KEY_PATH=\"./keys/jwt.key.pub\"" >> .env
          echo "PRIV_KEY_PATH=\"./keys/jwt.key\"" >> .env

      - name: Compose up
        run: docker compose up -d

      - name: NPM install
        run: npm install

      - name: Prettier format
        run: npx prettier . --check

      - name: Db migrations
        run: bash migrate.sh

      - name: Test
        run: npm run test

      - name: Compose down
        run: docker compose down -v
